name = "scheduler"
main = "src/index.js"
compatibility_date = "2026-01-30"

[observability]
enabled = true

[triggers]
crons = ["* * * * *"]

[[services]]
binding = "RUNNER"
service = "runner"

[[migrations]]
tag = "<v2>"
deleted_classes = [ "Ticker" ]
