name = "scheduler"
main = "src/index.js"
compatibility_date = "2026-01-30"

[observability]
enabled = true

[durable_objects]
bindings = [
  { name = "TICKER", class_name = "Ticker" }
]

[triggers]
crons = ["* * * * *"]

[[services]]
binding = "RUNNER"
service = "runner"

[[migrations]]
tag = "v4"
new_sqlite_classes = ["Ticker"]
